import type { Metadata } from "next";
import { Fjalla_One, Libre_Baskerville } from "next/font/google";
import "./globals.css";
import { ViewTransitions } from "next-view-transitions";

import ConditionalLayout from "./_components/conditional-layout";

const fjallaOne = Fjalla_One({
  subsets: ["latin"],
  variable: "--font-fjalla-one",
  weight: ["400"],
});

const libreBaskerville = Libre_Baskerville({
  subsets: ["latin"],
  variable: "--font-libre-baskerville",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Sarath Menon | Artist",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${fjallaOne.variable} ${libreBaskerville.variable} antialiased`}
      >
        <ViewTransitions>
          <ConditionalLayout>
            {children}
          </ConditionalLayout>
        </ViewTransitions>
      </body>
    </html>
  );
}
